firebase/firebase-functions-python

src/firebase_functions/https.py
Per onCall function protocol for response body (https://firebase.google.com/docs/functions/callable-reference#response_body), the oncall function should return a body with either `result` or `error`.
Given following oncall function:
```
@https.on_call()
def oncall(req: https.CallableRequest):
return "foo"
```
As implemented, it returns "data" and "status":
```
{
data: "foo"
status: 200
}
```
With fix:
```
{
result: "foo"
}
```
Fixes https://github.com/firebase/firebase-functions-python/issues/36
=> fix: conform to protocol specification for https oncall function

src/firebase_functions/options.py, src/firebase_functions/private/manifest.py, src/firebase_functions/private/serving.py, src/firebase_functions/private/util.py, tests/test_options.py
=> feat: RESET_VALUE

docs/generate.sh
Reference docs preview Zip download: https://github.com/firebase/firebase-functions-python/suites/12292609308/artifacts/651325813
=> docs: update path & add missing modules

src/firebase_functions/firestore_fn.py
In the emulated environment, we must explicitly pass the project id for the Firestore Client per https://github.com/googleapis/python-firestore/blob/15872858332b56fefcb40fdfbc4df9320cd5ed75/google/cloud/firestore_v1/base_client.py#L133
=> fix: Wire up firestore reference in emulated environment.

src/firebase_functions/test_lab_fn.py, tests/test_test_lab_fn.py
Client Info details can be optional in some scenarios, this now defaults to empty dict if the key does not exist.
Fixes #64
=> fix(test_lab): client info details can be undefined (fixes #64)

samples/basic_db/functions/main.py, src/firebase_functions/db_fn.py
Formerly a string only.
Deployed the following function; 
```python
from firebase_functions import db_fn, options
from firebase_admin import initialize_app
initialize_app()
options.set_global_options(region=options.SupportedRegion.EUROPE_WEST1)
@db_fn.on_value_written(reference="hello/world", instance="a-non-default-database")
def onwriteexample(event: db_fn.Event[db_fn.Change]) -> None:
print("Hello from db write event:", event)
print("Reference.path:", event.reference.path)
print("Reference.get():", event.reference.get())
```
Edited /hello/world on Firebase console to have the value `"some data in my hello/world ref woo!"`, this successfully triggered, logs shown below (note the none default database instance and non default region used in the deployed code to verify correct instance is …
=> refactor(db)!: reference is now instance of a Database reference

src/firebase_functions/private/serving.py
Allow import of relative files in `main.py` by adding the cwd to the sys.path. Otherwise getting /__/functions.yaml will raise an exception that imports could not be found.
There's probably a better way to do this but my python foo is a little rusty.
Closes #92
=> fix: add cwd to sys.path for functions yaml

.gitignore, .vscode/settings.json, example/functions/main.py, samples/basic_alerts/functions/main.py
Currently, the CI fails because of formatting changes. This PR formats all the code to fix the same
=> chore: fix CI failure due for incorrect formatting

src/firebase_functions/firestore_fn.py, src/firebase_functions/private/util.py, tests/test_util.py
This PR should be merged first to fix the formatting CI failure: https://github.com/firebase/firebase-functions-python/pull/108
Created a util function for normalizing Firestore document paths for each Firestore event listener.
fix #91 
We tested the implementation by running Functions emulator. Here is a sample log of the path coming into the function before and after the path is normalized:
Print logs to show before and after we normalize the path:
Output on the console for "created", "written", "updated" & "deleted":
We've also created a unit test for the normalize function [here](https://github.com/firebase/firebase-functions-python/pull/106/files#diff-0dcbadaa6c70afb6fea041dec04bb89c3cc7fe201fb7c3185a669efa49769f28R45-R60)
=> fix: normalize firestore document path

src/firebase_functions/core.py, src/firebase_functions/https_fn.py
Just a few things in core and https for now.  If the process works without issues with CI or permissions or whatever, I'd like to send some more tweaks.  Thanks!
=> Making some style and format fixes.

src/firebase_functions/private/path_pattern.py, tests/test_path_pattern.py
A leading forward slash will add an additional segment when extracting pattern matching elements causing an out of range index error.
fixes https://github.com/firebase/firebase-functions-python/issues/113
=> fix: handle leading forward slash in pattern matching path function

src/firebase_functions/private/util.py
I removed an invalid argument to a logging.warning call.
https://github.com/firebase/firebase-functions-python/issues/130
As-is, the logging block for missing content-type headers is:
```py
def _on_call_valid_content_type(request: _Request) -> bool:
"""Validate content"""
content_type: str | None = request.headers.get("Content-Type")
if content_type is None:
_logging.warning("Request is missing Content-Type.", content_type)
return False
...
```
In the conditional block, you can see the None positional arg `content_type` passed to the logging call. Python logging doesn't allow null positional (nor keyword) args. The logging used in this module is indeed stdlib Python logging cf [functions-framework-python](https://github.com/GoogleCloudPlatform/functions-framework-python/blob/main/src/funct …
=> fix: issue with logging

src/firebase_functions/private/util.py
From the [Python 3.11 docs](), emphasis added:
"""
debug(msg, *args, **kwargs)
Logs a message with level [DEBUG](https://docs.python.org/3/library/logging.html#logging.DEBUG) on this logger. The msg is the _message format string, and the args are the arguments which are merged into msg using the string formatting operator_. (Note that this means that you can use keywords in the format string, together with a single dictionary argument.) _No % formatting operation is performed on msg when no args are supplied_.
"""
The simplest reproducible error case is: `python -c 'import logging; logging.warning("asdf", "qwer");'`
The expected result is a stack trace.
To fix: `logger.warning("asdf %s", "qwer");`
Please note that the firebase-functions-python codebase has a tremendous number of instances …
=> fix the most egregious issue with the use of python logging

src/firebase_functions/private/util.py
https://github.com/firebase/firebase-functions-python/issues/136
=> fix: precision timestamp detection issue

src/firebase_functions/identity_fn.py, src/firebase_functions/private/_identity_fn.py, src/firebase_functions/private/token_verifier.py, src/firebase_functions/private/util.py
Fixes https://github.com/firebase/firebase-functions-python/issues/133
Fixes https://github.com/firebase/firebase-functions-python/issues/144
=> fix: crash with `InvalidAuthBlockingTokenError`

src/firebase_functions/firestore_fn.py, src/firebase_functions/private/_alerts_fn.py, src/firebase_functions/private/util.py, tests/test_util.py
According to  [rfc3339](https://www.ietf.org/rfc/rfc3339.txt) timestamp protobuf could have optionally the fractional seconds. This change improves the current `src/firebase_functions/private/util.py` to convert the dates when there are no fractional seconds.
Fixes #148
=> fix: handle timestamps with no fractional seconds

src/firebase_functions/private/_identity_fn.py
When using blocking function for phone auth, it crashes, because the dict does not seem to include "email_verified" param.
=> fix: Crash in auth blocking function when using with phone auth

src/firebase_functions/logger.py, src/firebase_functions/private/_identity_fn.py, src/firebase_functions/private/util.py, tests/test_logger.py
=> feat: implement logger

src/firebase_functions/identity_fn.py, src/firebase_functions/logger.py, src/firebase_functions/private/_identity_fn.py
See https://github.com/firebase/firebase-functions/pull/1458
=> feat: add reCAPTCHA verdict to auth blocking functions

setup.py
Python type annotations are not exported by default. In order to export types, you have to mark the package with a `py.typed` file (empty file) or publish types in an external location like `typeshed`. This PR introduces the `py.typed` file for the `firebase_functions` package.
More information on exporting types:
- https://mypy.readthedocs.io/en/stable/installed_packages.html
- https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
- https://peps.python.org/pep-0561/
=> Types are not exported

samples/basic_params/functions/main.py, src/firebase_functions/params.py, src/firebase_functions/private/manifest.py, tests/test_manifest.py, tests/test_params.py
Reverts firebase/firebase-functions-python#85
=> feat: add support for ListParam & MultiSelectInput

src/firebase_functions/__init__.py
Starting in 2024, PyPI has made changes that require adding GitHub Actions as a Trusted Publisher in order to publish packages via our GitHub release workflow. This reverts the PR that triggered the broken release so that we can make the necessary changes to our release workflow and publish to PyPI as a Trusted Publisher (see https://github.com/firebase/firebase-functions-python/pull/190).
This reverts commit ee9589d1a5ebe5e2f8e79755b86ec0c3d8efb589.
=> Revert "chore: Release 0.3.0 (#189)"

src/firebase_functions/__init__.py
https://github.com/firebase/firebase-functions-python/pull/189 failed due to a change to PyPI's publishing policy. We reverted the PR and deleted the corresponding 0.3.0 release and tag, so this is take 2. See https://github.com/firebase/firebase-functions-python/pull/190 for the release workflow modifications.
=> chore: Release 0.3.0

src/firebase_functions/firestore_fn.py
Fixes https://github.com/firebase/firebase-functions-python/issues/194
=> fix: KeyError for authtype

src/firebase_functions/logger.py
Currently, logger messages containing non-ascii characters are displayed as unicode escape sequences, making them illegible to anyone reading the logs.
For example,
```python
from firebase_functions import logger
logger.log("こんにちは")
```
This behavior is due to the logger module making use of `json.dumps` which by default only outputs ascii characters (see [here](https://docs.python.org/3/library/json.html#json.dumps)).
I added `ensure_ascii=False` to wherever `json.dumps` was used for the logger messages and now output for these logs should be legible.
```python
logger.log("こんにちは")
```
Let me know if there are any questions or issues 👍
=> make non-ascii characters in logger messages legible

src/firebase_functions/firestore_fn.py
=> fix: incorrect type for document snapshop in Firestore auth triggers

src/firebase_functions/options.py, tests/test_options.py
=> fix: Off by one assertion for invoker property

setup.py, src/firebase_functions/logger.py
Resolves #226 
Note: changing `google-events>=0.5.0` to `google-events==0.5.0` is due to breaking changes in a later version (than 0.5.0) of `google-events` causing linting to fail. Failure can be seen [here](https://github.com/firebase/firebase-functions-python/actions/runs/12363926530/job/34506216421).
=> fix(logger): set utf-8 encoding

.pylintrc, setup.py, src/firebase_functions/params.py, src/firebase_functions/private/manifest.py, tests/test_manifest.py, tests/test_params.py
To resolve [this issue](https://github.com/firebase/firebase-functions-python/issues/209)
Note: changing `google-events>=0.5.0` to `google-events==0.5.0` is due to breaking changes in a later version (than 0.5.0) of `google-events` causing linting to fail. Failure can be seen [here](https://github.com/firebase/firebase-functions-python/actions/runs/12119305084/job/33785597146).
=> fix: FloatParam marked private as unsupported in CLI

.github/workflows/ci.yaml, .github/workflows/release.yaml
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> chore(workflows): update upload-artifact to v4 as v3 deprecated

src/firebase_functions/logger.py, tests/test_logger.py
Resolves https://github.com/firebase/firebase-functions-python/issues/228
=> fix(logger): no longer replaces object duplicates with "CIRCULAR"

setup.py
Resolves https://github.com/firebase/firebase-functions-python/issues/234
=> chore: update cloudevents dependency to use >=1.2.0 and <2.0.0

src/firebase_functions/identity_fn.py, src/firebase_functions/private/_identity_fn.py
Resolves https://github.com/firebase/firebase-functions-python/issues/224
=> fix(identity): AuthBlockingEvent properties not matching docs

src/firebase_functions/__init__.py
The previous PR that was merged had a small typo that didn't end up triggering the release GitHub action.
=> chore: Release 0.4.3 (take 2)
